[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "forge-std/=/home/josh/onyxfinance/PeridotWormholeFoundry/backend/lib/forge-std/src/",
    "witnet-solidity-bridge/=/home/josh/onyxfinance/PeridotWormholeFoundry/backend/lib/witnet-solidity-bridge/"
]
evm_version = "shanghai"